# golangci-lint configuration
# For more info: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  skip-dirs-use-default: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable-all: false
  enable:
    # Code quality
    - asasalint        # Check for pass []any as any in variadic func(...)any
    - asciicheck       # Simple linter to check that your code does not contain non-ASCII identifiers
    - bidichk          # Checks for dangerous unicode character sequences
    - bodyclose        # Checks whether HTTP response body is closed successfully
    - contextcheck     # Check whether the function uses a non-inherited context
    - cyclop           # Check function and package cyclomatic complexity
    - dogsled          # Checks assignments with too many blank identifiers (e.g. num, _, _, _, := NextInt())
    - dupl             # Tool for code clone detection
    - dupword          # Checks for duplicate words in comments
    - errcheck         # Errcheck is a program for checking for unchecked errors in go programs
    - errchkjson       # Checks types passed to the json encoding functions
    - errorlint        # Find code that will cause problems with the error wrapping scheme introduced in Go 1.13
    - execinquery      # Checks query string in Query function
    - exportloopref    # Checks for pointers to enclosing loop variables
    - gci              # Gci control golang package import order and make it always deterministic
    - gochecknoglobals # Check for global variables
    - gochecknoinits   # Checks that no init functions are present in Go code
    - gocognit         # Computes and checks the cognitive complexity of functions
    - goconst          # Finds repeated strings that could be replaced by a constant
    - gocritic         # Provides diagnostics that the standard Go compiler doesn't give you
    - gocyclo          # Computes and checks the cyclomatic complexity of functions
    - godox            # Tool for detection of FIXME, TODO and other comment keywords
    - gofmt            # Gofmt checks whether code was gofmt-ed
    - goimports        # Goimports does everything that gofmt does
    - gomnd            # An analyzer to detect magic numbers
    - gomodguard       # Allow and block lists linter for direct Go module dependencies
    - goprintffuncname # Checks that printf-like functions are named with f at the end
    - gosec            # Inspects source code for security problems
    - gosimple         # Linter for Go source code that specializes in simplifying code
    - govet            # Vet examines Go source code and reports suspicious constructs
    - grouper          # An analyzer to analyze expression groups
    - ineffassign      # Detects when assignments to existing variables are not effectively used
    - interfacebloat   # A linter that checks the number of methods inside an interface
    - intrange         # Intrange is a linter to find places where for loops could make use of an integer range
    - ireturn          # Accept Interfaces, Return Concrete Types
    - lll              # Reports long lines
    - loggercheck      # Checks key value pairs for common logger libraries
    - misspell         # Finds commonly misspelled English words in comments
    - musttag          # Enforce field tags in (un)marshaled structs
    - nilerr           # Finds the code that returns nil and an error
    - nilnil           # Checks that there is no simultaneous return of nil error and an invalid value
    - nolintlint       # Reports ill-formed or insufficient nolint directives
    - nonamedreturns   # Reports all named returns
    - nosprintfhostport # Checks for misuse of Sprintf to construct a host with port in a URL
    - perfsprint       # Checks that fmt.Sprintf can be replaced with a faster alternative
    - prealloc         # Finds slice declarations that could potentially be pre-allocated
    - predeclared      # Finds code that shadows one of Go's predeclared identifiers
    - revive           # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - rowserrcheck     # Checks whether Rows.Err is checked successfully
    - sloglint         # Ensure consistent code style when using log/slog
    - sqlclosecheck    # Checks that sql.Rows and sql.Stmt are closed
    - staticcheck      # Staticcheck is a go vet on steroids, applying tons of static analysis checks
    - stylecheck       # Stylecheck is a replacement for golint
    - tagalign         # Check that struct tags are well aligned
    - tagliatelle      # Checks the struct tags
    - tenv             # Tenv is a linter for Go that is checking for non-parallel execution of test cases
    - testableexamples # Linter checks if examples are testable (have an expected output)
    - tparallel        # Tparallel detects inappropriate usage of t.Parallel() method in your Go test code
    - unconvert        # Remove unnecessary type conversions
    - underscoreinplace # Checks for the usage of an underscore in variable assignment
    - unparam          # Reports unused function parameters
    - unused           # Checks Go code for unused constants, variables, functions and types
    - usestdlibvars    # A linter that detect the possibility to use variables/constants from the Go standard library
    - wastedassign     # Finds wasted assignment statements
    - whitespace       # Tool for detection of leading and trailing whitespace

  disable:
    - exhaustruct      # Checks if all struct fields are initialized
    - exhaustivestmt   # Checks if all enum members are explicitly handled in switch statements
    - forcetypeassert  # Forbids an expression with an explicit type cast where the value is already of that type
    - nlreturn         # Checks for a new line before return and branch statements
    - wrapcheck        # Checks that errors returned from external packages are wrapped

issues:
  exclude-use-default: true
  exclude-rules:
    # Allow _ as unused arguments in functions
    - source: "^\\s+_ = .*\\.$"
      linters:
        - ineffassign
    # Allow tests to be less strict
    - path: "_test\\.go"
      linters:
        - gocyclo
        - gosec
        - govet
        - lll

linters-settings:
  cyclop:
    max-complexity: 10
  funlen:
    lines: 60
    statements: 40
  gocognit:
    min-complexity: 15
  gocyclo:
    min-complexity: 10
  gocritic:
    enabled-checks:
      - nestingLevel
      - unnamedResult
      - hugeParam
  gomnd:
    ignored-numbers:
      - "0"
      - "1"
      - "2"
      - "-1"
      - "100"
  lll:
    line-length: 120
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: duplicated-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: indent-error-flow
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: superfluous-else
      - name: time-equal
      - name: time-naming
      - name: unexported-return
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver
      - name: var-declaration
      - name: var-naming
  stylecheck:
    dot-import-whitelist:
      - fmt
