version: 2

project_name: mcpgate

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: mcpgate
    main: ./main.go
    binary: mcpgate

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64
      - arm

    goarm:
      - "7"

    env:
      - CGO_ENABLED=0

    flags:
      - -trimpath

    ldflags:
      - -s -w
      - -X github.com/j4ng5y/mcpgate/cmd.Version={{.Version}}
      - -X github.com/j4ng5y/mcpgate/cmd.Commit={{.Commit}}
      - -X github.com/j4ng5y/mcpgate/cmd.Date={{.Date}}

upx:
  - enabled: true
    compress: 9
    lzma: true
    brute: true
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    ids:
      - mcpgate

archives:
  - id: mcpgate-archive
    builds:
      - mcpgate
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}_{{ .Arm }}{{ end }}
      {{- if .Mips }}_{{ .Mips }}{{ end }}

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch

release:
  github:
    owner: j4ng5y
    name: mcpgate
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
